pipeline {
    agent any
  environment {
    // SEMGREP_BASELINE_REF = ""

        SEMGREP_APP_TOKEN = credentials('SEMGREP_APP_TOKEN')
        SEMGREP_PR_ID = "${env.CHANGE_ID}"

      //  SEMGREP_TIMEOUT = "300"
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
                sh '''
                    echo "WORKSPACE=$WORKSPACE"
            
                    echo "Current directory:"
                    pwd
            
                    echo ""
            
                    echo "Workspace contents:"
                    ls -la "$WORKSPACE"
            
                    echo ""
            
                    echo "WebGoat folder contents:"
                    ls -la "$WORKSPACE/WebGoat"
                '''
            }
        }
        stage('GitLeaks Scan') {
            steps {
                sh '''
                docker run --rm \
                -v "$WORKSPACE/WebGoat:/repo" \
                zricethezav/gitleaks:latest \
                detect \
                --source /repo \
                --verbose
                '''
            }
        }
        stage('Semgrep Scan') {
            steps {
              dir('WebGoat') {
                sh '/var/jenkins_home/semgrep-venv/bin/semgrep ci'
              }
            }
        }
        stage('Build') {
            steps {
                dir('WebGoat') {
                   sh './mvnw clean install'
                }
            }
        }
    }
}
