pipeline {
    agent any

    environment {
        SEMGREP_APP_TOKEN = credentials('SEMGREP_APP_TOKEN')
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                sh './mvnw clean install'
            }
        }

        stage('Semgrep Scan') {
            steps {
                sh '/var/jenkins_home/semgrep-venv/bin/semgrep ci'
            }
        }
    }
}
